### PR TITLE
Merge to TiKV 6.3(b5329ee) into Proxy

### PR DESCRIPTION
**Pull request by CalvinNeo**
### What problem does this PR solve?

Issue Number: close #xxx

Problem Summary:

### Check List

Tests 

- [ ] Unit test
- [ ] Integration test
- [ ] Manual test (add detailed scripts or steps below)
- [ ] No code

Side effects

- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [ ] Breaking backward compatibility

Documentation

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Changes MySQL compatibility

### Release note

```release-note
None
```

### CODE REVIEW

**Comment by CalvinNeo** [comment]
maybe a merge commit is better to resolve later conflicts.

**Review by breezewish — APPROVED** [review]

**Review by breezewish — APPROVED** [review]

**Comment by purelind** [comment]
ci image need fixed by https://github.com/PingCAP-QE/ci/pull/1446

**Pull request merged**
